apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: f2s-service-rolebinding
subjects:
  - kind: ServiceAccount
    name: f2s-service
    namespace: f2s
roleRef:
  kind: ClusterRole
  name: f2s-service-role
  apiGroup: rbac.authorization.k8s.io
