{
 "title": "F2S Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "replicas" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes / 1024 / 1024",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Incoming Requests Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum(rate(f2s_requests_total[15s])) by (functionname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum(f2s_active_requests_total) by (functionname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time since last Request Completion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - f2s_last_request_timestamp) by (functionname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests - Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(f2s_request_duration_seconds_bucket) by (functionname)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}