apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: f2s
data:
  prometheus.rules: |-
    groups: []
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system:8080']
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'kube_deployment_status_replicas_.*'
            action: keep
          - source_labels: [namespace]
            regex: 'f2s-containers'
            action: keep
