apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: f2s
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  selector:
    app: f2s-prometheus
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
