debug: true

prometheus:
  url: 192.168.2.40:32133

f2s:
  memberlist:
    bind_port: 7079
    cluster: memberlist.f2s
  timeouts:
    request_timeout: 120000
    http_timeout: 60000
    scaling_timeout: 4000
  auth:
    global_config:
      type: none
    basic:
      - username: roman
        password: helloworld
        group: admins
    token:
      tokens:
        - token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjQyMzc4OTgsImdyb3VwIjoiZ3JvdXAxIiwic3ViIjoicm9tYW4ifQ.xQOtzG2cNa4eg97qidR-YN7v3qyJ18qjShWYLFUs_bU
      jwt_secret: test
    authorization:
      - group: admins
        privileges:
          - functions:list
          - functions:invoke
          - functions:create
          - functions:delete
          - functions:update
          - settings:view
          - settings:update
  kafka:
    enabled: false
    brokers:
      - 192.168.2.41:30051
      - 192.168.2.42:30052
      - 192.168.2.43:30053
      # - kafka-1.kafka
    listeners:
      - topic: test-topic
        consumergroup: f2s-consumer
        actions:
          - name: test-action
            triggers:
              - type: key
                filter: equal
                value: test-key
            f2sfunctions:
              - ffe4eb97-3716-479f-8cd4-f86d05bb8e99
              # - fb790e7d-506d-4817-9336-400d147b12f4
            response:
              key: test-response
