apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: f2s
data:
  prometheus.rules: |-
    groups:
    - name: recording_rules
      rules:
        # number of requests/sec completed by all available function-containers
        - record: f2sscaling_function_requests_completed_rate
          expr: sum(rate(f2s_requests_completed_total[15s])) by (functionname)

        # number of available function containers
        - record: f2sscaling_function_deployment_available_replicas
          expr: sum(kube_deployment_status_replicas_available) by (functionname)

        # how many req/s can one function container perform
        - record: f2sscaling_function_completion_performance_per_container_request_rate
          expr: f2sscaling_function_requests_completed_rate / f2sscaling_function_deployment_available_replicas

        # Incoming Request Rate for Function
        - record: f2sscaling_function_incoming_request_rate
          expr: sum by(functionname) (rate(f2s_requests_incoming_total[15s]))

        # Requests Backlog Growth for Function
        - record: f2sscaling_function_requests_backlog_growth_rate
          # expr: ((sum by(functionname) (delta(f2s_active_requests_total[15s]))) > 0 / 15) or on() vector(0)
          expr: (sum (clamp_min(delta(f2s_active_requests_total[15s]),0)) by (functionname)) / 15

        # Current Scaling Decision based on available replicas and (incoming requests + backlog growth)
        # - can be "-1" for scaling down 1 replica for example
        # - can be "12" for scaling up 12 replicase for example
        - record: f2sscaling_function_scaling_decision_replicas_difference
          expr: (f2sscaling_function_containers_required_total - on(functionname) kube_deployment_status_replicas_available) or on() kube_deployment_status_replicas_available{functionname="$functionname"} * -1

        # track ready replicas of f2s in order to decice who is master (lowest alphabetical guid)
        - record: f2s_master_election_ready_pods
          expr: kube_pod_status_ready{pod=~"f2s-operator.+"} == 1

        - record: job:function_duration_average:sec
          expr: avg(f2s_request_duration_seconds_sum / f2s_request_duration_seconds_count) by(functionname)

        - record: job:function_capacity_average:reqpersec
          expr: 1000 / (max_over_time(delta(f2s_requests_duration_total[15s])[24h:]) / on(podUID, functionname) max_over_time(delta(f2s_requests_completed_total[15s])[24h:]))

        # calculated number of containers needed to perform the incoming requests
        - record: job:function_containers_required:containers
          expr: ceil(sum(f2sscaling_function_incoming_request_rate) by (functionname) / sum(job:function_capacity_average:reqpersec) by (functionname))
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system:8080']
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'kube_deployment_status_replicas_.*|kube_pod_status_ready'
            action: keep
          - source_labels: [namespace]
            regex: 'f2s|f2s-containers'
            action: keep
          - source_labels: [__name__, deployment]
            separator: ";"
            regex: '(kube_deployment_status_replicas_available);(.*)'
            target_label: 'functionname'
            replacement: '${2}'
            action: replace
      - job_name: 'f2s-metrics'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - f2s
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: 8081
            action: keep
        metrics_path: /metrics
