apiVersion: "apiextensions.k8s.io/v1"
kind: CustomResourceDefinition
metadata:
  name: "functions.f2s.opensight.ch"
spec:
  group: "f2s.opensight.ch"
  scope: "Namespaced"
  names:
    plural: "functions"
    singular: "function"
    kind: "Function"
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["endpoint", "method"]
              properties:
                endpoint:
                  type: "string"
                method:
                  type: "string"
                description:
                  type: "string"
            target:
              type: object
              required:
                [
                  "containerImage",
                  "port",
                  "endpoint",
                  "minReplicas",
                  "maxReplicas",
                ]
              properties:
                containerImage:
                  type: "string"
                port:
                  type: "integer"
                endpoint:
                  type: "string"
                maxReplicas:
                  type: "integer"
                  default: 1
                minReplicas:
                  type: "integer"
                  default: 1
