apiVersion: v1
kind: ConfigMap
metadata:
  name: f2s-conf
  labels:
    name: f2s-conf
  namespace: f2s
data:
  config.yaml: |-
    debug: true

    prometheus:
      url: prometheus-service.f2s:9090
