apiVersion: v1
kind: ConfigMap
metadata:
  name: f2s-conf
  labels:
    name: f2s-conf
  namespace: f2s
data:
  config.yaml: |-
    debug: true

    prometheus:
      url: prometheus-service.f2s:9090

    f2s:
      timeouts:
        request_timeout: 120000
        http_timeout: 60000
        scaling_timeout: 45000
      auth:
        global_config:
          type: none
      #   basic:
      #     - username: roman
      #       password: helloworld
      #       group: admins
      #   token:
      #     tokens:
      #       - token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjQyMzc4OTgsImdyb3VwIjoiZ3JvdXAxIiwic3ViIjoicm9tYW4ifQ.xQOtzG2cNa4eg97qidR-YN7v3qyJ18qjShWYLFUs_bU
      #     jwt_secret: test
      #   authorization:
      #     - group: admins
      #       privileges:
      #         - functions:list
      #         - functions:invoke
      #         - functions:create
      #         - functions:delete
      #         - functions:update
      #         - settings:view
      #         - settings:update
      # kafka:
      #   enabled: false
      #   brokers:
      #     - kafka-1.kafka
      #   listeners:
      #     - topic: test
      #       actions:
      #         - triggers:
      #             - type: key
      #               filter: equal
      #               value: test-key
      #           f2sfunctions:
      #             - xxxxxxxxxx
      #           response:
      #             key: test-response
