apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: f2s-service-role
rules:
  - apiGroups: [""]
    resources:
      ["pods", "replicationcontrollers", "persistentvolumeclaims", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["f2s.opensight.ch"]
    resources: ["functions"]
    verbs: ["get", "list", "watch", "delete", "create", "update"]
