apiVersion: v1
kind: Service
metadata:
  name: f2s-api
  namespace: f2s
  labels:
    app: f2sapi
spec:
  selector:
    app: f2s
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: f2s-metrics
  namespace: f2s
  labels:
    app: f2smetrics
spec:
  selector:
    app: f2s
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
