openapi: 3.0.3
info:
  title: F2S API
  description: F2S Function as a Service Platform
  version: 1.0.0

tags:
  - name: Configuration
    description: Manage F2S Configuration
  - name: Containers
    description: Interact with F2S-Containers K8S Namespace

paths:
  /functions:
    get:
      summary: get all configured functions
      tags:
        - Configuration
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  kind:
                    type: string
                  apiVersion:
                    type: string
                  metadata:
                    type: object
                  items:
                    type: array
                    items:
                      type: object

  /functions/{id}:
    get:
      summary: get specific function
      tags:
        - Configuration
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string

  /deployments:
    get:
      summary: get all current f2s deployments
      tags:
        - Containers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  kind:
                    type: string
                  apiVersion:
                    type: string
                  metadata:
                    type: object
                  items:
                    type: array
                    items:
                      type: object
    post:
      summary: create a test deployment
      tags:
        - Containers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
