name: publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get TAG
        id: get_tag
        run: echo TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      - name: Generate new Release
        run: |
          python3 -m pip install -r ./utility/requirements.txt
          python3 ./utility/create_release.py ${{ env.TAG }}

      - name: Commit Helm Chart Archive and Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name ${{ env.REPO_OWNER }}
          git checkout --track origin/main
          git add ./helm-release/*.tgz
          git add ./helm-release/index.yaml
          git add ./helm/Chart.yaml
          git commit -m "helm-release-${{ env.TAG }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./f2soperator
          file: ./f2soperator/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          tags: |
            romanhuesler/f2s:${{ github.sha }}
            romanhuesler/f2s:${{ env.TAG }}
            romanhuesler/f2s:latest
