name: publish-examples

on:
  push:
    tags:
      - "examples-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get TAG
        id: get_tag
        run: echo TAG=${GITHUB_REF#refs/tags/} | sed 's/examples-//' >> $GITHUB_ENV

      # nodejs testcontainer
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./examples/container_nodejs_test
          file: ./examples/container_nodejs_test/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          tags: |
            romanhuesler/f2snodejstest:${{ env.TAG }}
            romanhuesler/f2snodejstest:latest

      # python testcontainer
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./examples/container_python_test
          file: ./examples/container_python_test/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          tags: |
            romanhuesler/f2spythontest:${{ env.TAG }}
            romanhuesler/f2spythontest:latest

      # python datefinder
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./examples/container_python_datefinder
          file: ./examples/container_python_datefinder/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          tags: |
            romanhuesler/f2spythondatefinder:${{ env.TAG }}
            romanhuesler/f2spythondatefinder:latest

      # nodejs guessdateformat
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./examples/container_nodejs_guessdateformat
          file: ./examples/container_nodejs_guessdateformat/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          tags: |
            romanhuesler/f2snodejsguessdateformat:${{ env.TAG }}
            romanhuesler/f2snodejsguessdateformat:latest
