name: publish-fizzlet

on:
  push:
    tags:
      - "fizzlet-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get TAG
        id: get_tag
        run: echo TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./f2sfizzlet
          file: ./f2sfizzlet/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          tags: |
            romanhuesler/f2sfizzlet:${{ github.sha }}
            romanhuesler/f2sfizzlet:${{ env.TAG }}
            romanhuesler/f2sfizzlet:latest
